import type { LucideIcon } from 'lucide-react';
import {
  AlertCircle,
  BookOpen,
  ChevronDown,
  ChevronRight,
  FileText,
  GitCommitHorizontal,
  LayoutDashboard,
  Lock,
  ScrollText,
  ShieldCheck,
  Workflow,
} from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useEventSubscribe } from '@/hooks/use-event-stream';
import { renderMarkdown } from '@/lib/markdown';
import { cn } from '@/lib/utils';
import { OverviewTab } from './overview-tab';

interface FileEntry {
  path: string;
  exists: boolean;
  content: string;
}

interface RuleGroup {
  layer: string;
  files: FileEntry[];
}

interface ProjectFilesResponse {
  conventions: FileEntry;
  knowledge: FileEntry;
  claudeMd: FileEntry;
  rules: RuleGroup[];
}

interface TabMeta {
  value: 'overview' | 'knowledge' | 'claude' | 'rules';
  label: string;
  description: string;
  icon: LucideIcon;
}

const TABS: TabMeta[] = [
  {
    value: 'overview',
    label: 'Overview',
    description: 'Project identity, tech stack, and metadata at a glance.',
    icon: LayoutDashboard,
  },
  {
    value: 'knowledge',
    label: 'Knowledge',
    description:
      'Project memory: domain glossary, gotchas, external-integration quirks, and lessons learned. Agents append here after a task surfaces something non-obvious so the next agent doesn’t re-learn it.',
    icon: BookOpen,
  },
  {
    value: 'claude',
    label: 'CLAUDE.md',
    description: 'Top-level project context shared with every Claude session.',
    icon: ScrollText,
  },
  {
    value: 'rules',
    label: 'Rules',
    description:
      'Non-overridable rules every agent must respect. project.md is generated by /caw-setup; the other two ship with caw.',
    icon: ShieldCheck,
  },
];

function MarkdownView({ entry }: { entry: FileEntry }) {
  if (!entry.exists) {
    return (
      <div className="flex items-center gap-2 text-muted-foreground text-sm italic py-12 justify-center">
        <AlertCircle className="size-4" />
        <span>
          <code className="font-mono">{entry.path}</code> not found in project.
        </span>
      </div>
    );
  }
  if (!entry.content.trim()) {
    return (
      <p className="text-muted-foreground text-sm italic py-12 text-center">
        File exists but is empty.
      </p>
    );
  }
  return (
    <div>
      <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground font-mono mb-4 pb-3 border-b border-border/60">
        <FileText className="size-3" />
        <span>{entry.path}</span>
      </div>
      <div
        className="prose-task max-w-none"
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: renderMarkdown(entry.content) }}
      />
    </div>
  );
}

// Order + metadata for the 3 whitelisted rule files surfaced in the UI.
// The API also enforces this whitelist; this array controls display order
// and per-file labels.
const RULE_FILES: {
  filename: string;
  label: string;
  blurb: string;
  icon: LucideIcon;
  // 'project' = generated per-project; 'caw' = ships with caw
  origin: 'project' | 'caw';
}[] = [
  {
    filename: 'project.md',
    label: 'Project rules',
    blurb:
      'Stack lock-ins, forbidden patterns, and domain rules specific to this project. Generated by /caw-setup.',
    icon: Lock,
    origin: 'project',
  },
  {
    filename: 'commit-conventions.md',
    label: 'Commit conventions',
    blurb: 'How commits and PRs are formatted across this repo.',
    icon: GitCommitHorizontal,
    origin: 'caw',
  },
  {
    filename: 'harness-contract.md',
    label: 'Harness contract',
    blurb: 'Triggers and protocol for when agents emit decisions, ADRs, and reviews.',
    icon: Workflow,
    origin: 'caw',
  },
];

interface RuleRow {
  meta: (typeof RULE_FILES)[number];
  entry: { layer: string; file: FileEntry };
}

function RuleAccordionItem({
  row,
  open,
  onToggle,
}: {
  row: RuleRow;
  open: boolean;
  onToggle: () => void;
}) {
  const { meta, entry } = row;
  const RuleIcon = meta.icon;
  const isProject = meta.origin === 'project';
  const hasBody = entry.file.exists && entry.file.content.trim().length > 0;

  return (
    <div
      className={cn(
        'rounded-xl border overflow-hidden transition-colors',
        open ? 'border-primary/50 bg-primary/3' : 'border-border/60 bg-muted/15',
      )}
    >
      {/* Header — clickable */}
      <button
        type="button"
        onClick={onToggle}
        className="group/rule w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-muted/30 transition-colors"
      >
        <div
          className={cn(
            'size-9 rounded-lg flex items-center justify-center shrink-0 transition-colors',
            open ? 'bg-primary/15 text-primary' : 'bg-muted/60 text-muted-foreground',
          )}
        >
          <RuleIcon className="size-4" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <span
              className={cn(
                'text-[13.5px] font-semibold truncate',
                open ? 'text-primary' : 'text-foreground',
              )}
            >
              {meta.label}
            </span>
            <span
              className={cn(
                'shrink-0 text-[8.5px] font-semibold uppercase tracking-wider px-1.5 py-0.5 rounded',
                isProject ? 'bg-primary/15 text-primary' : 'bg-muted text-muted-foreground/70',
              )}
            >
              {isProject ? 'project' : 'caw'}
            </span>
          </div>
          <p className="text-[11px] text-muted-foreground/70 leading-relaxed truncate mt-0.5">
            {meta.blurb}
          </p>
        </div>
        <span className="text-[10px] text-muted-foreground/50 font-mono hidden sm:block shrink-0">
          {entry.layer}/{meta.filename}
        </span>
        {open ? (
          <ChevronDown className="size-4 text-muted-foreground/60 shrink-0" />
        ) : (
          <ChevronRight className="size-4 text-muted-foreground/60 shrink-0" />
        )}
      </button>

      {/* Body — expanded */}
      {open && (
        <div className="border-t border-border/50">
          <div className="flex items-center gap-1.5 px-4 py-2 bg-muted/20 text-[11px] text-muted-foreground/60 font-mono">
            <FileText className="size-3 shrink-0" />
            <span>{entry.file.path}</span>
          </div>
          <div className="px-5 py-4">
            {hasBody ? (
              <div
                className="prose-task max-w-none"
                // eslint-disable-next-line react/no-danger
                dangerouslySetInnerHTML={{ __html: renderMarkdown(entry.file.content) }}
              />
            ) : (
              <p className="text-muted-foreground text-sm italic py-6 text-center">
                {entry.file.exists ? 'File exists but is empty.' : 'File not found in project.'}
              </p>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

function RulesView({ groups }: { groups: RuleGroup[] }) {
  // Flatten to filename-keyed map and only render the curated whitelist.
  const byFilename = new Map<string, { layer: string; file: FileEntry }>();
  for (const g of groups)
    for (const f of g.files) {
      const name = f.path.split('/').pop() || f.path;
      if (!byFilename.has(name)) byFilename.set(name, { layer: g.layer, file: f });
    }

  const ordered: RuleRow[] = RULE_FILES.map((r) => ({
    meta: r,
    entry: byFilename.get(r.filename),
  })).filter((x): x is RuleRow => !!x.entry);

  // First rule expanded by default.
  const [openKey, setOpenKey] = useState<string | null>(ordered[0]?.meta.filename ?? null);

  if (ordered.length === 0) {
    return (
      <div className="flex items-center gap-2 text-muted-foreground text-sm italic py-12 justify-center">
        <AlertCircle className="size-4" />
        <span>
          No rules found in <code className="font-mono">.claude/rules/</code>.
        </span>
      </div>
    );
  }

  return (
    <div className="space-y-2.5">
      {ordered.map((row) => (
        <RuleAccordionItem
          key={row.meta.filename}
          row={row}
          open={openKey === row.meta.filename}
          onToggle={() => setOpenKey((k) => (k === row.meta.filename ? null : row.meta.filename))}
        />
      ))}
    </div>
  );
}

function getEntryForTab(tab: TabMeta['value'], data: ProjectFilesResponse): FileEntry | null {
  if (tab === 'knowledge') return data.knowledge;
  if (tab === 'claude') return data.claudeMd;
  return null;
}

function isTabEmpty(tab: TabMeta['value'], data: ProjectFilesResponse): boolean {
  if (tab === 'overview' || tab === 'rules') return false;
  const entry = getEntryForTab(tab, data);
  return !entry?.exists || !entry.content.trim();
}

export function ProjectInfo() {
  const [data, setData] = useState<ProjectFilesResponse | null>(null);
  const [loading, setLoading] = useState(true);

  const load = useCallback(() => {
    fetch('/api/project-files.json')
      .then((r) => r.json())
      .then((d: ProjectFilesResponse) => setData(d))
      .catch(() => undefined)
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    load();
  }, [load]);
  useEventSubscribe(['project-files'], load);

  const ruleCount = data?.rules.reduce((sum, g) => sum + g.files.length, 0) ?? 0;

  return (
    <div>
      <div className="card-border-glow rounded-2xl overflow-hidden">
        <div className="px-6 py-5 border-b border-border/40 flex items-start justify-between gap-4">
          <div className="space-y-1">
            <h2 className="text-base font-semibold tracking-tight">Project Info</h2>
            <p className="text-sm text-muted-foreground">
              Source-of-truth files driving agent behavior in this project.
            </p>
          </div>
        </div>

        {loading ? (
          <div className="p-6 space-y-3">
            <Skeleton className="h-8 w-1/3" />
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-5/6" />
            <Skeleton className="h-4 w-4/6" />
          </div>
        ) : !data ? (
          <div className="p-12 text-center text-muted-foreground text-sm">
            Could not load project files.
          </div>
        ) : (
          <Tabs defaultValue="overview" className="flex flex-col">
            <div className="px-6 pt-4 bg-muted/20 border-b border-border">
              <TabsList
                variant="line"
                className="h-auto p-0 bg-transparent gap-1 w-full justify-start overflow-x-auto"
              >
                {TABS.map((t) => {
                  const Icon = t.icon;
                  const empty = isTabEmpty(t.value, data);
                  return (
                    <TabsTrigger
                      key={t.value}
                      value={t.value}
                      className={cn(
                        'gap-2 rounded-none border-b-2 border-transparent',
                        'data-[state=active]:border-primary data-[state=active]:text-primary data-[state=active]:bg-transparent',
                        'px-3 py-2.5 text-sm',
                        empty && 'opacity-50',
                      )}
                    >
                      <Icon className="size-4" />
                      <span>{t.label}</span>
                      {t.value === 'rules' && ruleCount > 0 && (
                        <Badge
                          variant="secondary"
                          className="ml-1 h-5 px-1.5 text-[10px] font-mono"
                        >
                          {ruleCount}
                        </Badge>
                      )}
                    </TabsTrigger>
                  );
                })}
              </TabsList>
            </div>

            {TABS.map((t) => (
              <TabsContent key={t.value} value={t.value} className="m-0 outline-none">
                <div className="px-6 pt-4 pb-3 border-b border-border/60 bg-muted/10">
                  <p className="text-[12.5px] text-muted-foreground leading-relaxed">
                    {t.description}
                  </p>
                </div>
                <div className="px-6 py-6">
                  {t.value === 'overview' ? (
                    <OverviewTab />
                  ) : t.value === 'rules' ? (
                    <RulesView groups={data.rules} />
                  ) : (
                    <MarkdownView entry={getEntryForTab(t.value, data)!} />
                  )}
                </div>
              </TabsContent>
            ))}
          </Tabs>
        )}
      </div>
    </div>
  );
}
