import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { APIRoute } from 'astro';
import { IS_STATIC } from '@/lib/deploy-target';
import { isDevMode, MOCK_OVERVIEW } from '@/lib/mock-data';
import { readProjectMeta } from '@/lib/project-meta';
import { getProjectRoot } from '@/lib/project-root';
import { getProjectName } from '@/lib/task-parser';

export const prerender = IS_STATIC;

// Legacy fallback — only used when project.yaml is absent (project hasn't
// re-run /caw-setup --refresh since the YAML pipeline shipped).
async function resolveNameLegacy(root: string): Promise<string> {
  const [conventions, claudeMd] = await Promise.all([
    readFile(join(root, '.claude', 'conductor', 'conventions.md'), 'utf8').catch(() => ''),
    readFile(join(root, 'CLAUDE.md'), 'utf8').catch(() => ''),
  ]);
  const convH1 = conventions.match(/^#\s+(.+?)\s*$/m);
  if (convH1) {
    const cleaned = convH1[1]
      .replace(/^Project Conventions\s*[—\-:]\s*/i, '')
      .replace(/^Conventions\s*[—\-:]\s*/i, '')
      .trim();
    if (cleaned && cleaned.toLowerCase() !== 'project conventions') return cleaned;
  }
  const claudeH1 = claudeMd.match(/^#\s+(.+?)\s*$/m);
  if (claudeH1) {
    const cleaned = claudeH1[1].replace(/\s*[—\-:].*$/, '').trim();
    if (cleaned && cleaned.toUpperCase() !== 'CLAUDE.MD') return cleaned;
  }
  return getProjectName(root);
}

export const GET: APIRoute = async () => {
  const root = getProjectRoot();
  if (isDevMode(root)) {
    return new Response(JSON.stringify({ name: MOCK_OVERVIEW.name, root }), {
      status: 200,
      headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' },
    });
  }
  // Primary path: structured project.yaml (deterministic, generated by script).
  const meta = await readProjectMeta(root);
  const name = meta?.name ?? (await resolveNameLegacy(root));
  return new Response(JSON.stringify({ name, root }), {
    status: 200,
    headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' },
  });
};
